source_set("partition_extension_autoloader") {
  sources = [
    "partition_extension_autoloader.cc",
    "partition_extension_autoloader.h",
    "partition_extension_autoloader_factory.cc",
    "partition_extension_autoloader_factory.h",
  ]

  deps = [
    "//base",
    "//chrome/browser/profiles:profile",
    "//components/keyed_service/content",
    "//components/pref_registry",
    "//components/prefs",
    "//content/public/browser",
    "//extensions/browser",
    "//chromium_src/overlay/chrome/browser/multi_session",
  ]
}

