source_set("multi_session_dialog") {
  sources = [
    "multi_session_open_dialog.cc",
    "multi_session_open_dialog.h",
  ]

  deps = [
    "//base",
    "//chrome/browser/ui",
    "//chromium_src/overlay/chrome/browser/multi_session",
    "//ui/gfx",
    "//ui/views",
    "//url",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [
    "multi_session_open_dialog_unittest.cc",
  ]

  deps = [
    ":multi_session_dialog",
    "//chrome/test:test_support",
    "//testing/gtest",
  ]
}
